--  ★ 테이블과 시퀀스 중복 유뮤 확인
DROP TABLE STUDENT;
DROP SEQUENCE STUDENT_NO_SEQ;

--  ★ 테이블과 시퀀스 생성
CREATE TABLE STUDENT (
    SNO NUMBER(9) PRIMARY KEY,
    SNAME VARCHAR2(30) NOT NULL,
    MAJOR VARCHAR2(50),
    SCORE NUMBER(3)
);

CREATE SEQUENCE STUDENT_NO_SEQ
    MAXVALUE 999999999
    NOCACHE
    NOCYCLE;
    
--  ★ 기본적인 데이터 입력
SELECT *
    FROM STUDENT;

INSERT INTO STUDENT
    VALUES (STUDENT_NO_SEQ.NEXTVAL, '유비', '경제', 96);
    
INSERT INTO STUDENT
    VALUES (STUDENT_NO_SEQ.NEXTVAL, '관우', '경호', 90);
    
INSERT INTO STUDENT
    VALUES (STUDENT_NO_SEQ.NEXTVAL, '장비', '건축', 89);
 
    