-- �쁾VIEW, INLINE VIEW, TOP-N 援щЦ
--	1. VIEW : 媛��긽�쓽 �뀒�씠釉�
--		1) �떒�닚 酉� : �븯�굹�쓽 �뀒�씠釉붾줈 援ъ꽦�븳 酉�
CREATE OR REPLACE  VIEW EMPv0
	AS SELECT EMPNO, ENAME, JOB, DEPTNO
	FROM EMP;

--			�몺 DDL�쓣 �닔�젙�븯硫� �뜲�씠�꽣�궗吏꾩씠 �옄�룞 �닔�젙
SELECT *
	FROM USER_VIEWS;

SELECT *
	FROM EMPv0;

SELECT *
	FROM EMP;

--			�몼 酉곗뿉 �궡�슜 異붽� 諛� �닔�젙
INSERT INTO EMPV0 
	VALUES (9000, 'HONG', 'MANAGER', 40);

UPDATE EMPv0
	SET JOB = 'ANALYST'
	WHERE EMPNO = 9000;

DELETE FROM EMPv0
	WHERE EMPNO = 9000;

--				EMPv0�씠�씪�뒗 酉곕뒗 EMP�뀒�씠釉붿씠 30踰덉씤 遺��꽌留� �븸�꽭�뒪 媛��뒫
CREATE OR REPLACE VIEW EMPv0
	AS SELECT *
		FROM EMP
		WHERE DEPTNO = 30;

SELECT *
	FROM EMPv0;

INSERT INTO EMPV0 
	VALUES (1111, 'HONG', NULL, NULL, NULL, NULL, NULL, 30);

SELECT * 
	FROM EMPv0 
	WHERE EMPNO = 1111;

SELECT *
	FROM EMP 
	WHERE EMPNO = 1111;

INSERT INTO EMPv0 
	VALUES (1112, 'KIM', NULL, NULL, NULL, NULL, NULL, 40);

SELECT *
	FROM EMP 
	WHERE EMPNO < 2000;
--				諛⑷툑 �엯�젰�븳 1111, 1112瑜� �궘�젣�븯�젮 �뻽�쑝�굹 30踰덈��꽌留� �궘�젣�릪. 1112�뒗 �궘�젣 �븞�릪
DELETE FROM EMPv0 
	WHERE EMPNO < 2000;

SELECT *
	FROM EMP 
	WHERE EMPNO < 2000;

--			�몾 而щ읆�뿉 蹂꾩묶�쓣 �궗�슜�븯�뿬 酉곕�� �깮�꽦 (�븘�뱶�뿉 �듅�닔臾몄옄媛� �엳�뒗 寃쎌슦)
CREATE OR REPLACE VIEW EMPv1 
	AS SELECT EMPNO NO, ENAME NAME, (SAL*12) YEAR_SAL
		FROM EMP
		WHERE DEPTNO = 10;
	
SELECT *
	FROM EMPv1;

INSERT INTO EMPv1 -- 媛��긽�쓽 �븘�뱶媛� �엳�뼱�꽌 媛깆떊 遺덇�
	VALUES (1000, 'HONG', 12000);

CREATE OR REPLACE VIEW EMPv1 (EMPNO, ENAME, YEAR_SAL)
	AS SELECT EMPNO, ENAME, SAL*12
		FROM EMP
		WHERE DEPTNO = 10;
	
--			�몾 - 1 �궗踰�, �씠由�, 10�옄由ъ뿉�꽌 諛섏삱由� �븳 SAL�쓣 酉곕줈 �깮�꽦
CREATE OR REPLACE VIEW EMPv1 (EMPNO, ENAME, ROUND_SAL)
	AS SELECT EMPNO, ENAME, ROUND(SAL, -2)
		FROM EMP;

SELECT *
	FROM EMPv1;
	
--		1-1) 酉곗쓽 �젣�븳 議곌굔
--			�몺 WITH CHECK OPTION�쓣 �꽕�젙�븳 酉곕뒗 議곌굔�뿉 �빐�떦�릺�뒗 �뜲�씠�꽣留� �궫�엯, �닔�젙, �궘�젣 媛��뒫
CREATE OR REPLACE VIEW EMPv0
	AS SELECT *
		FROM EMP
		WHERE DEPTNO  = 30
		WITH CHECK OPTION;

INSERT INTO EMPv0 
	VALUES (1111, '�솉', NULL, NULL, NULL, NULL, NULL, 30);

SELECT *
	FROM EMPv0;

SELECT *
	FROM EMP;

INSERT INTO EMPv0 -- 議곌굔�쓣 留뚯”�븯吏� 紐삵븯湲� �븣臾몄뿉 �뿉�윭 諛쒖깮
	VALUES (1113, '諛�', NULL, NULL, NULL, NULL, NULL, 40);

DELETE FROM EMPv0 
	WHERE EMPNO = 1111;

--			�몼 WITH READ ONLY �꽕�젙�쓣 �븳 酉곕뒗 �씫湲� �쟾�슜 酉�
CREATE OR REPLACE VIEW EMPv1
	AS SELECT *
		FROM EMP
		WHERE DEPTNO = 20
		WITH READ ONLY;
	
SELECT E.*, DNAME
	FROM EMPv1 E, DEPT D 
	WHERE E.DEPTNO = D.DEPTNO;

--				�씫湲� �쟾�슜�씠湲� �븣臾몄뿉 �뿉�윭 諛쒖깮
INSERT INTO EMPv1
	VALUES (1114, '�쑄', NULL, NULL, NULL, NULL, NULL, 20);

UPDATE EMPv1
	SET SAL = 9000
	WHERE EMPNO = 7902;

--			�몾 �뀒�씠釉붿뿉 NOT NULL濡� 留뚮뱺 而щ읆�� 諛섎뱶�떆 �룷�븿�릺�뼱�빞 �븿.



--		2) 蹂듯빀 酉� : �몢媛� �씠�긽�쓽 �뀒�씠釉붾줈 援ъ꽦�맂 酉�
--						DML臾몄쓣 �젣�븳�쟻�쑝濡쒕쭔 �궗�슜媛��뒫.
CREATE OR REPLACE VIEW EMPv0
	AS SELECT EMPNO, ENAME, JOB, DNAME
		FROM EMP E, DEPT D
		WHERE E.DEPTNO = D.DEPTNO;

SELECT *
    FROM EMPv0;
    
INSERT INTO EMPv0 -- 蹂듯빀酉곕뒗 媛깆떊 遺덇�
    VALUES (1200, 'HONG', 'MANAGER', 'RESEARCH');

--		2-1) �뿰�뒿臾몄젣
--			�몺 遺��꽌踰덊샇, 理쒖냼湲됱뿬, 理쒕�湲됱뿬, �룊洹좉툒�뿬瑜� �룷�븿�븳 DEPTv1 酉곕�� �깮�꽦
CREATE OR REPLACE VIEW DEPTv1 (DEPTNO, MINSAL, MAXSAL, AVGSAL)
	AS SELECT DEPTNO, MIN(SAL), MAX(SAL), ROUND(AVG(SAL), 2)
		FROM EMP
		GROUP BY DEPTNO;
   
  SELECT *
  	FROM DEPTv1;
  
 --			�몼 遺��꽌踰덊샇, 遺��꽌紐�, 理쒖냼湲됱뿬, 理쒕�湲됱뿬, �룊洹좉툒�뿬瑜� �룷�븿�븳 DEPTv2 酉� �깮�꽦
 CREATE OR REPLACE VIEW DEPTv2
 	AS SELECT D.DEPTNO, DNAME, MINSAL, MAXSAL, AVGSAL
 		FROM DEPTv1 DV, DEPT D
 		WHERE DV.DEPTNO = D.DEPTNO;
   
 SELECT *
 	FROM DEPTv2;

 --			�몾 DISTINCT瑜� �씠�슜�븳 酉� : 以묐났�씠 �젣嫄곕맖
CREATE OR REPLACE VIEW EMPv0 
	AS SELECT DISTINCT JOB, DEPTNO
		FROM EMP;
   
SELECT *
	FROM EMPv0;

INSERT INTO EMPv0 -- DISTINCT濡� �씤�빐 以묐났 遺덇�
	VALUES ('MANAGER', 10);
   
   
   
--		3) INLINE VIEW : FROM�젅�긽�쓽 �꽌釉뚯옘由�, FROM�젅�뿉 �삤�뒗 �꽌釉뚯옘由щ뒗
--								酉곗쿂�읆 �옉�슜�븳�떎.
--			SELECT �븘�뱶1, �븘�뱶2,....
--				FROM �뀒�씠釉붾챸, (�꽌釉뚯옘由�) 蹂꾩묶
--				WHERE 議곗씤議곌굔
--			�몺 湲됱뿬媛� 2000�쓣 珥덇낵�븯�뒗 �궗�썝�쓽 �룊洹� 湲됱뿬
SELECT ROUND(AVG(SAL), 2)
	FROM EMP
	WHERE SAL > 2000;

SELECT ROUND(AVG(SAL), 2)
	FROM (SELECT SAL FROM EMP WHERE SAL > 2000);

--			�몼 媛� 遺��꽌�뿉�꽌 遺��꽌 �룊洹좉툒�뿬蹂대떎 �넂�� �궗�썝�쓽 �씠由�, 湲됱뿬, 遺��꽌踰덊샇
SELECT ENAME, SAL, DEPTNO
	FROM EMP E
	WHERE SAL > (SELECT AVG(SAL) FROM EMP WHERE DEPTNO = E.DEPTNO);
   
--		 3-1) �뿰�뒿臾몄젣
--			�몺�떒怨� : 遺��꽌 踰덊샇 蹂� �룊洹� 湲됱뿬
SELECT DEPTNO, ROUND(AVG(SAL), 2)
	FROM EMP
	GROUP BY DEPTNO;
 
--			�몼�떒怨� : �씠由�, 湲됱뿬, 遺��꽌踰덊샇, 遺��꽌蹂꾪룊洹�
SELECT ENAME, SAL, E.DEPTNO, AVGSAL
	FROM EMP E, (SELECT DEPTNO, ROUND(AVG(SAL), 2) AVGSAL
					FROM EMP
					GROUP BY DEPTNO) S
	WHERE E.DEPTNO = S.DEPTNO;

--			�몾�떒怨� : �씠由�, 湲됱뿬, 遺��꽌踰덊샇(遺��꽌蹂꾪룊洹좊낫�떎 �넂�� �궗�썝留�)
SELECT ENAME, SAL, E.DEPTNO, AVGSAL
	FROM EMP E, (SELECT DEPTNO, ROUND(AVG(SAL), 2) AVGSAL
					FROM EMP
					GROUP BY DEPTNO) S
	WHERE E.DEPTNO = S.DEPTNO AND SAL > AVGSAL;
   
   
 
--		4) TOP-N : (EX. 1~10�벑, 11~20�벑, 6~10�벑)
--		�쁾 ROWNUM : �뀒�씠釉붾줈遺��꽣 �뜲�씠�꽣瑜� 媛��졇�삩 �닚�꽌瑜� 蹂댁뿬以�! 
SELECT ROWNUM, ENAME
	FROM EMP
	WHERE DEPTNO = 20;

DELETE FROM EMP
	WHERE SAL IS NULL;
   
SELECT ROWNUM, ENAME, SAL
	FROM EMP;

SELECT ROWNUM, ENAME, SAL
	FROM EMP
	ORDER BY SAL;

SELECT ROWNUM, ENAME, SAL
	FROM (SELECT * FROM EMP ORDER BY SAL);

--			�몺 SAL 湲곗��쑝濡� 1~5�벑 異쒕젰
SELECT ROWNUM, ENAME, SAL
	FROM (SELECT ENAME, SAL FROM EMP ORDER BY SAL)
	WHERE ROWNUM < 6;
	
--			�몼 �븿�닔瑜� �씠�슜�븳 �벑�닔 異쒕젰
SELECT 	RANK () OVER(ORDER BY SAL) RANK,    
		DENSE_RANK () OVER(ORDER BY SAL) D_RANK,
		ROW_NUMBER () OVER(ORDER BY SAL) N_RANK,
		ENAME, SAL
	FROM EMP;
   
--			�몾 SAL 湲곗��쑝濡� 6~10�벑 異쒕젰 (�븞�릺�뒗 �삁�떆)
SELECT ROWNUM, ENAME, SAL
	FROM (SELECT ENAME, SAL FROM EMP ORDER BY SAL)
	WHERE ROWNUM >= 6 OR ROWNUM <= 10;  
   
--			�몿 TOP-N 쿼리
--				1단계
SELECT ROWNUM, SAL
	FROM EMP
	ORDER BY SAL;

--				2단계
SELECT ROWNUM RN, ENAME, SAL
	FROM (SELECT ENAME, SAL FROM EMP ORDER BY SAL);
   
--				3단계  
SELECT ROWNUM, RN, ENAME, SAL
	FROM (SELECT ROWNUM RN, ENAME, SAL
			FROM (SELECT ENAME, SAL
					FROM EMP
					ORDER BY SAL));
   
SELECT ROWNUM, RN, ENAME, SAL
	FROM (SELECT ROWNUM RN, ENAME, SAL
			FROM (SELECT *
					FROM EMP 
					ORDER BY SAL))
	WHERE RN BETWEEN 6 AND 10;
   
--			�몿-1 臾몄젣
--	�씠由꾩쓣 �븣�뙆踰� �닚�꽌��濡� �젙�젹�빐�꽌 6~10�벑源뚯� 異쒕젰
--	(�벑�닔, �씠由�, �궗踰�, JOB, MGR, HIREDATE)
--	1단계
SELECT ROWNUM, ENAME, EMPNO, JOB, MGR, HIREDATE
	FROM EMP
	ORDER BY ENAME;

--	2단계   
SELECT ROWNUM RN, ENAME, EMPNO, JOB, MGR, HIREDATE
	FROM (SELECT ENAME, EMPNO, JOB, MGR, HIREDATE
			FROM EMP
			ORDER BY ENAME);

--	3단계
SELECT RN, ENAME, EMPNO, JOB, MGR, HIREDATE
	FROM (SELECT ROWNUM RN, A.*
			FROM (SELECT ENAME, EMPNO, JOB, MGR, HIREDATE
					FROM EMP
					ORDER BY ENAME) A) -- �꽌釉뚯옘由� 蹂꾩묶
	WHERE RN BETWEEN 6 AND 10;



--		★ 연습문제
-- 			1. 부서명과 사원명을 출력하는 용도의 뷰, DNAME_ENAME_VU 를 작성하시오
CREATE OR REPLACE VIEW DNAME_ENAME_VU
	AS SELECT DNAME, ENAME
		FROM DEPT D, EMP E
		WHERE D.DEPTNO = E.DEPTNO;
		
SELECT *
	FROM DNAME_ENAME_VU ;

-- 			2. 사원명과 직속상관명을 출력하는 용도의 뷰,  WORKER_MANAGER_VU를 작성하시오
CREATE OR REPLACE VIEW WORKER_MANAGER_VU
	AS SELECT W.ENAME WORKER, M.ENAME MANAGER 
		FROM EMP W, EMP M 
		WHERE W.MGR = M.EMPNO(+);
		
SELECT *
	FROM WORKER_MANAGER_VU;

-- 			3. 부서별 급여합계 등수를 출력하시오(부서번호, 급여합계, 등수). – 친구출제
SELECT DEPTNO, SUMSAL, ROWNUM RANK_
	FROM (SELECT DEPTNO, SUM(SAL) SUMSAL
			FROM EMP 
			GROUP BY DEPTNO
			ORDER BY SUMSAL DESC) D;

-- 			3-1. 부서별 급여합계 등수가 2~3등인 부서번호, 급여합계, 등수를 출력하시오.
SELECT RN RANK, DEPTNO, SUMSAL
	FROM (SELECT ROWNUM RN, D.*
			FROM (SELECT DEPTNO, SUM(SAL) SUMSAL
					FROM EMP
					GROUP BY DEPTNO 
					ORDER BY SUMSAL) D)
	WHERE RN != 1;

-- 			4. 사원테이블에서 사번, 사원명, 입사일을 입사일이 최신에서 오래된 사원 순으로 정렬하시오
SELECT RN, EMPNO, ENAME, HIREDATE
	FROM (SELECT ROWNUM RN, A.*
			FROM (SELECT EMPNO, ENAME, HIREDATE
					FROM EMP
					ORDER BY HIREDATE DESC) A);

-- 			5. 사원테이블에서 사번, 사원명, 입사일을 입사일이 최신에서 오래된 사원 5명을 출력하시오
SELECT RN, EMPNO, ENAME, HIREDATE
	FROM (SELECT ROWNUM RN, A.*
			FROM (SELECT EMPNO, ENAME, HIREDATE
					FROM EMP
					ORDER BY HIREDATE DESC) A)
	WHERE RN BETWEEN 1 AND 5;

-- 			6. 사원 테이블에서 사번, 사원명, 입사일을 최신부터 오래된 순으로 6번째로 늦은 사원부터 10번째 사원까지 출력
SELECT RN, EMPNO, ENAME, HIREDATE
	FROM (SELECT ROWNUM RN, A.*
			FROM (SELECT EMPNO, ENAME, HIREDATE
					FROM EMP
					ORDER BY HIREDATE DESC) A)
	WHERE RN BETWEEN 6 AND 10;